name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Versions
      shell: bash
      run: |
        rustup --version
        cargo --version
        rustc --version

    - name: Cache
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build [Debug]
      run: cargo build --verbose

    - name: Build [Release]
      run: cargo build --release --verbose

    - name: Create zips
      shell: bash
      run: |
        python3 - <<'!EOF'
        from zipfile import ZipFile, ZIP_DEFLATED

        with ZipFile("amax-redirect-release.zip", "w", compression=ZIP_DEFLATED) as zf:
            zf.write("./target/i686-pc-windows-msvc/release/amax_redirect.dll", "amax/dlls/amax_redirect.asi")
            zf.write("./amax/config/amax-redirect.cfg", "amax/config/amax-redirect.cfg")

        with ZipFile("amax-redirect-debug.zip", "w", compression=ZIP_DEFLATED) as zf:
            zf.write("./target/i686-pc-windows-msvc/debug/amax_redirect.dll", "amax/dlls/amax_redirect.asi")
            zf.write("./target/i686-pc-windows-msvc/debug/amax_redirect.pdb", "amax/dlls/amax_redirect.pdb")
            zf.write("./amax/config/amax-redirect.cfg", "amax/config/amax-redirect.cfg")
        !EOF

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: windows-build
        path: |
          ./amax-redirect-debug.zip
          ./amax-redirect-release.zip

    - name: Publish to GitHub releases
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        gh release create "${EPOCHREALTIME}-build-${GITHUB_SHA}" \
          ./amax-redirect-debug.zip \
          ./amax-redirect-release.zip \
          --title "$TAG" \
          --notes "Automated build artifacts" \
          --prerelease
