name: Build amax-redirects.asi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Versions
      shell: bash
      run: |
        rustup --version
        cargo --version
        rustc --version

    - name: Cache
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    # - name: Install nightly
    #   run: |
    #     rustup toolchain install nightly-x86_64-pc-windows-msvc
    #     rustup default nightly
    #     rustup target add i686-pc-windows-msvc

    - name: Build [Debug]
      run: cargo build --verbose
    - name: Build [Release]
      run: cargo build --release --verbose

    - name: Upload artifact [Debug]
      uses: actions/upload-artifact@v7
      with:
        name: windows-build-debug
        path: |
          ./target/i686-pc-windows-msvc/debug/amax_redirect.dll
          ./target/i686-pc-windows-msvc/debug/amax_redirect.pdb

    - name: Upload artifact [Release]
      uses: actions/upload-artifact@v7
      with:
        name: windows-build-release
        path: |
          ./target/i686-pc-windows-msvc/release/amax_redirect.dll

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows]

    steps:
    - name: Download Windows artifacts [Debug]
      uses: actions/download-artifact@v8
      with:
        name: windows-build-debug
        path: ./release-assets/windows-debug
    - name: Download Windows artifacts [Release]
      uses: actions/download-artifact@v8
      with:
        name: windows-build-debug
        path: ./release-assets/windows-release


    # TODO: amax_redirect.zip/{debug,release}/amax-redirects.{asi,pdb}

    - name: Publish [Debug] binaries to GitHub releases
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "${EPOCHREALTIME}-build-${GITHUB_SHA}-Debug" \
          ./release-assets/windows-debug/amax_redirect.dll \
          ./release-assets/windows-debug/amax_redirect.pdb \
          --title "$TAG" \
          --notes "Automated build artifacts" \
          --prerelease

    - name: Publish [Release] binaries to GitHub releases
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "${EPOCHREALTIME}-build-${GITHUB_SHA}-Release" \
          ./release-assets/windows-release/amax_redirect.dll \
          --title "$TAG" \
          --notes "Automated build artifacts" \
          --prerelease
