name: Build amax-redirects.asi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      
    - name: Install nightly
      run: |
        rustup toolchain install nightly-x86_64-pc-windows-msvc
        rustup default nightly
        rustup target add i686-pc-windows-msvc

    - name: Build debug [msvc]
      run: cargo +nightly build --verbose --target=i686-pc-windows-msvc
      
    - name: Build release [msvc]
      run: cargo +nightly build --verbose --release --target=i686-pc-windows-msvc
      
    - name: Collect debug artifact
      uses: actions/upload-artifact@v4
      with:
        name: amax-redirects_debug
        path: |
          ./target/i686-pc-windows-msvc/debug/amax_redirect.dll
          ./target/i686-pc-windows-msvc/debug/amax_redirect.pdb

    - name: Collect release artifact
      uses: actions/upload-artifact@v4
      with:
        name: amax-redirects_release
        path: |
          ./target/i686-pc-windows-msvc/release/amax_redirect.dll
